### DISCUSSION TITLE
Couple of issues im struggling with

### DISCUSSION THREAD

**Discussion by sverrevr** [ethz-asl/wavemap#76] [Q&A]
**Parts of the map never update:**
Even flying around for a while, parts of the map never get any voxels
![image](https://github.com/user-attachments/assets/e1310e33-8a20-4d74-b036-ff38c31431fc)

With the following config:
```
general:
  world_frame: "map"
  logging_level: info
  allow_reset_map_service: true

map:
  type: hashed_chunked_wavelet_octree
  min_cell_width: { meters: 0.2 }

map_operations:
  - type: threshold_map
    once_every: { seconds: 2.0 }
  - type: prune_map
    once_every: { seconds: 10.0 }
  - type: publish_map
    once_every: { seconds: 0.1 }

measurement_integrators:
  ouster_os0_low_res:
    projection_model:
      type: spherical_projector
      elevation:
        num_cells: 64
        min_angle: { degrees: -45.73 }
        max_angle: { degrees: 46.27 }
      azimuth:
        num_cells: 512
        min_angle: { degrees: -180.0 }
        max_angle: { degrees: 180.0 }
    measurement_model:
      type: continuous_beam
      angle_sigma: { degrees: 0.1}
      range_sigma: { meters: 0.05 }
      scaling_free: 0.5
      scaling_occupied: 0.5
    integration_method:
      type: hashed_chunked_wavelet_integrator
      min_range: { meters: 0.3 }
      max_range: { meters: 5 }
      max_update_resolution: { meters: 0.2 }

inputs:
  - type: pointcloud_topic
    topic_name: "/scan_registration_node/preprocessed_cloud_tte"
    topic_type: PointCloud2
    measurement_integrator_names: ouster_os0_low_res
    undistort_motion: false
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }
```

I'm guessing this is due to the center of the cell being further behind the wall than range sigma. So should range_sigma >= max_update_resolution/2? 

Doubling range sigma solves this, but has the following problem:

**Ghost voxels around robot:**
If I increase the range sigma to 0.1, then occupied voxels appear around the drone, even though there are no points in the pointcloud here
![image](https://github.com/user-attachments/assets/20f9529b-fe38-4f5f-a1a5-a631925aa6db)

Reducing range sigma to 0.05 resolves the issue:
![image](https://github.com/user-attachments/assets/6d8eb59a-bf29-4802-beaa-474f9e24a62c)

The problem persists if I switch to continuous_ray with angle_sigma 0.1
![image](https://github.com/user-attachments/assets/eb7d377f-1ed5-4e79-9a9a-d2269bb51464)

** Parts of obstacles not represented**
With angle sigma 0.1, and range sigma 0.1
![image](https://github.com/user-attachments/assets/6217141c-9e80-465c-895f-537add24e845)

We see that a part of a thin wall that is clearly seen by the lidar is marked as free-space

Here we are looking at a long and flap lamp. Parts of the reflection are outside of the voxels,
![image](https://github.com/user-attachments/assets/ba97f348-b240-45fe-8e9f-54a212b38b42)

**Reducing run-time:**
I tried solving this by using multiple integrator with different ranges:
```
general:
  world_frame: "map"
  logging_level: info
  allow_reset_map_service: true

map:
  type: hashed_chunked_wavelet_octree
  min_cell_width: { meters: 0.05 }

map_operations:
  - type: threshold_map
    once_every: { seconds: 2.0 }
  - type: prune_map
    once_every: { seconds: 10.0 }
  - type: publish_map
    once_every: { seconds: 0.1 }

measurement_integrators:
  ouster_os0_short:
    projection_model:
      type: spherical_projector
      elevation:
        num_cells: 64
        min_angle: { degrees: -45.73 }
        max_angle: { degrees: 46.27 }
      azimuth:
        num_cells: 512
        min_angle: { degrees: -180.0 }
        max_angle: { degrees: 180.0 }
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.025 }
      scaling_free: 0.5
      scaling_occupied: 0.5
    integration_method:
      type: hashed_chunked_wavelet_integrator
      min_range: { meters: 0.5 }
      max_range: { meters: 1 }
      max_update_resolution: { meters: 0.05 }

  ouster_os0_mid:
    projection_model:
      type: spherical_projector
      elevation:
        num_cells: 64
        min_angle: { degrees: -45.73 }
        max_angle: { degrees: 46.27 }
      azimuth:
        num_cells: 512
        min_angle: { degrees: -180.0 }
        max_angle: { degrees: 180.0 }
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.05 }
      scaling_free: 0.5
      scaling_occupied: 0.5
    integration_method:
      type: hashed_chunked_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 3.0 }
      max_update_resolution: { meters: 0.1 }

  ouster_os0_long:
    projection_model:
      type: spherical_projector
      elevation:
        num_cells: 64
        min_angle: { degrees: -45.73 }
        max_angle: { degrees: 46.27 }
      azimuth:
        num_cells: 512
        min_angle: { degrees: -180.0 }
        max_angle: { degrees: 180.0 }
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.1 }
      scaling_free: 0.5
      scaling_occupied: 0.5
    integration_method:
      type: hashed_chunked_wavelet_integrator
      min_range: { meters: 3.0 }
      max_range: { meters: 5.0 }
      max_update_resolution: { meters: 0.2 }

inputs:
  - type: pointcloud_topic
    topic_name: "/scan_registration_node/preprocessed_cloud_tte"
    topic_type: PointCloud2
    measurement_integrator_names: [ouster_os0_short, ouster_os0_mid, ouster_os0_long]
    undistort_motion: false
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }

```
This greatly improved the map, but used too much CPU. 
Do you have any tips on how to reduce the CPU requirements?
